// Auto-generated by scripts/generate-shader.ts
// 12 parts × 36 vertices = 432 vertices total

struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(0) uv: vec2f,
}

struct Uniforms {
    time: f32,
    rotY: f32,
    rotX: f32,
    isSlim: f32,
    scale: f32,
    aspect: f32,
}

@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@group(1) @binding(0) var skin: texture_2d<f32>;
@group(1) @binding(1) var skin_sampler: sampler;

// ── matrix helpers ────────────────────────────────────────────────

fn mul4(a: mat4x4f, b: mat4x4f) -> mat4x4f {
    return mat4x4f(a * b[0], a * b[1], a * b[2], a * b[3]);
}
fn rotate_x(a: f32) -> mat4x4f {
    let c = cos(a); let s = sin(a);
    return mat4x4f(vec4f(1,0,0,0), vec4f(0,c,s,0), vec4f(0,-s,c,0), vec4f(0,0,0,1));
}
fn rotate_y(a: f32) -> mat4x4f {
    let c = cos(a); let s = sin(a);
    return mat4x4f(vec4f(c,0,-s,0), vec4f(0,1,0,0), vec4f(s,0,c,0), vec4f(0,0,0,1));
}

// ── cube geometry ─────────────────────────────────────────────────

const cube = array<vec3f, 36>(
    vec3f(-0.5, -0.5, 0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(-0.5, -0.5, 0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(-0.5, 0.5, -0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(-0.5, 0.5, -0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(-0.5, 0.5, -0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(-0.5, -0.5, 0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(-0.5, -0.5, 0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(-0.5, 0.5, -0.5)
);

const cube_uv = array<vec2f, 36>(
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1)
);

// ── body parts ────────────────────────────────────────────────────

struct Part { pos: vec3f, size: vec3f }

const parts = array<Part, 12>(
    Part(vec3f(0.0000, 0.7500, 0.0000), vec3f(0.5000, 0.5000, 0.5000)), // head
    Part(vec3f(0.0000, 0.1250, 0.0000), vec3f(0.5000, 0.7500, 0.2500)), // body
    Part(vec3f(-0.3750, 0.1250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // right_arm
    Part(vec3f(0.3750, 0.1250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // left_arm
    Part(vec3f(-0.1250, -0.6250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // right_leg
    Part(vec3f(0.1250, -0.6250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // left_leg
    Part(vec3f(0.0000, 0.7500, 0.0000), vec3f(0.5313, 0.5313, 0.5313)), // head_overlay
    Part(vec3f(0.0000, 0.1250, 0.0000), vec3f(0.5313, 0.7813, 0.2813)), // body_overlay
    Part(vec3f(-0.3750, 0.1250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)), // right_arm_overlay
    Part(vec3f(0.3750, 0.1250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)), // left_arm_overlay
    Part(vec3f(-0.1250, -0.6250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)), // right_leg_overlay
    Part(vec3f(0.1250, -0.6250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)) // left_leg_overlay
);

const phases = array<f32, 12>(0.0, 0.0, 1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 1.0, -1.0, -1.0, 1.0);
const pivot_y = 0.3750f;

// ── UV rectangles per part × face ─────────────────────────────────

struct FaceUV { min: vec2f, max: vec2f }

const uv_head = array<FaceUV, 6>(
    FaceUV(vec2f(0.12500, 0.12500), vec2f(0.25000, 0.25000)),
    FaceUV(vec2f(0.37500, 0.12500), vec2f(0.50000, 0.25000)),
    FaceUV(vec2f(0.12500, 0.00000), vec2f(0.25000, 0.12500)),
    FaceUV(vec2f(0.25000, 0.00000), vec2f(0.37500, 0.12500)),
    FaceUV(vec2f(0.25000, 0.12500), vec2f(0.37500, 0.25000)),
    FaceUV(vec2f(0.00000, 0.12500), vec2f(0.12500, 0.25000))
);

const uv_body = array<FaceUV, 6>(
    FaceUV(vec2f(0.31250, 0.31250), vec2f(0.43750, 0.50000)),
    FaceUV(vec2f(0.50000, 0.31250), vec2f(0.62500, 0.50000)),
    FaceUV(vec2f(0.31250, 0.25000), vec2f(0.43750, 0.31250)),
    FaceUV(vec2f(0.43750, 0.25000), vec2f(0.50000, 0.31250)),
    FaceUV(vec2f(0.43750, 0.31250), vec2f(0.50000, 0.50000)),
    FaceUV(vec2f(0.25000, 0.31250), vec2f(0.31250, 0.50000))
);

const uv_rarm = array<FaceUV, 6>(
    FaceUV(vec2f(0.68750, 0.31250), vec2f(0.75000, 0.50000)),
    FaceUV(vec2f(0.81250, 0.31250), vec2f(0.87500, 0.50000)),
    FaceUV(vec2f(0.68750, 0.25000), vec2f(0.75000, 0.31250)),
    FaceUV(vec2f(0.75000, 0.25000), vec2f(0.81250, 0.31250)),
    FaceUV(vec2f(0.75000, 0.31250), vec2f(0.81250, 0.50000)),
    FaceUV(vec2f(0.62500, 0.31250), vec2f(0.68750, 0.50000))
);

const uv_larm = array<FaceUV, 6>(
    FaceUV(vec2f(0.56250, 0.81250), vec2f(0.62500, 1.00000)),
    FaceUV(vec2f(0.68750, 0.81250), vec2f(0.75000, 1.00000)),
    FaceUV(vec2f(0.56250, 0.75000), vec2f(0.62500, 0.81250)),
    FaceUV(vec2f(0.62500, 0.75000), vec2f(0.68750, 0.81250)),
    FaceUV(vec2f(0.62500, 0.81250), vec2f(0.68750, 1.00000)),
    FaceUV(vec2f(0.50000, 0.81250), vec2f(0.56250, 1.00000))
);

const uv_rleg = array<FaceUV, 6>(
    FaceUV(vec2f(0.06250, 0.31250), vec2f(0.12500, 0.50000)),
    FaceUV(vec2f(0.18750, 0.31250), vec2f(0.25000, 0.50000)),
    FaceUV(vec2f(0.06250, 0.25000), vec2f(0.12500, 0.31250)),
    FaceUV(vec2f(0.12500, 0.25000), vec2f(0.18750, 0.31250)),
    FaceUV(vec2f(0.12500, 0.31250), vec2f(0.18750, 0.50000)),
    FaceUV(vec2f(0.00000, 0.31250), vec2f(0.06250, 0.50000))
);

const uv_lleg = array<FaceUV, 6>(
    FaceUV(vec2f(0.31250, 0.81250), vec2f(0.37500, 1.00000)),
    FaceUV(vec2f(0.43750, 0.81250), vec2f(0.50000, 1.00000)),
    FaceUV(vec2f(0.31250, 0.75000), vec2f(0.37500, 0.81250)),
    FaceUV(vec2f(0.37500, 0.75000), vec2f(0.43750, 0.81250)),
    FaceUV(vec2f(0.37500, 0.81250), vec2f(0.43750, 1.00000)),
    FaceUV(vec2f(0.25000, 0.81250), vec2f(0.31250, 1.00000))
);

const uv_head_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.62500, 0.12500), vec2f(0.75000, 0.25000)),
    FaceUV(vec2f(0.87500, 0.12500), vec2f(1.00000, 0.25000)),
    FaceUV(vec2f(0.62500, 0.00000), vec2f(0.75000, 0.12500)),
    FaceUV(vec2f(0.75000, 0.00000), vec2f(0.87500, 0.12500)),
    FaceUV(vec2f(0.75000, 0.12500), vec2f(0.87500, 0.25000)),
    FaceUV(vec2f(0.50000, 0.12500), vec2f(0.62500, 0.25000))
);

const uv_body_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.31250, 0.56250), vec2f(0.43750, 0.75000)),
    FaceUV(vec2f(0.50000, 0.56250), vec2f(0.62500, 0.75000)),
    FaceUV(vec2f(0.31250, 0.50000), vec2f(0.43750, 0.56250)),
    FaceUV(vec2f(0.43750, 0.50000), vec2f(0.50000, 0.56250)),
    FaceUV(vec2f(0.43750, 0.56250), vec2f(0.50000, 0.75000)),
    FaceUV(vec2f(0.25000, 0.56250), vec2f(0.31250, 0.75000))
);

const uv_rarm_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.68750, 0.56250), vec2f(0.75000, 0.75000)),
    FaceUV(vec2f(0.81250, 0.56250), vec2f(0.87500, 0.75000)),
    FaceUV(vec2f(0.68750, 0.50000), vec2f(0.75000, 0.56250)),
    FaceUV(vec2f(0.75000, 0.50000), vec2f(0.81250, 0.56250)),
    FaceUV(vec2f(0.75000, 0.56250), vec2f(0.81250, 0.75000)),
    FaceUV(vec2f(0.62500, 0.56250), vec2f(0.68750, 0.75000))
);

const uv_larm_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.81250, 0.81250), vec2f(0.87500, 1.00000)),
    FaceUV(vec2f(0.93750, 0.81250), vec2f(1.00000, 1.00000)),
    FaceUV(vec2f(0.81250, 0.75000), vec2f(0.87500, 0.81250)),
    FaceUV(vec2f(0.87500, 0.75000), vec2f(0.93750, 0.81250)),
    FaceUV(vec2f(0.87500, 0.81250), vec2f(0.93750, 1.00000)),
    FaceUV(vec2f(0.75000, 0.81250), vec2f(0.81250, 1.00000))
);

const uv_rleg_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.06250, 0.56250), vec2f(0.12500, 0.75000)),
    FaceUV(vec2f(0.18750, 0.56250), vec2f(0.25000, 0.75000)),
    FaceUV(vec2f(0.06250, 0.50000), vec2f(0.12500, 0.56250)),
    FaceUV(vec2f(0.12500, 0.50000), vec2f(0.18750, 0.56250)),
    FaceUV(vec2f(0.12500, 0.56250), vec2f(0.18750, 0.75000)),
    FaceUV(vec2f(0.00000, 0.56250), vec2f(0.06250, 0.75000))
);

const uv_lleg_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.06250, 0.81250), vec2f(0.12500, 1.00000)),
    FaceUV(vec2f(0.18750, 0.81250), vec2f(0.25000, 1.00000)),
    FaceUV(vec2f(0.06250, 0.75000), vec2f(0.12500, 0.81250)),
    FaceUV(vec2f(0.12500, 0.75000), vec2f(0.18750, 0.81250)),
    FaceUV(vec2f(0.12500, 0.81250), vec2f(0.18750, 1.00000)),
    FaceUV(vec2f(0.00000, 0.81250), vec2f(0.06250, 1.00000))
);

fn uv_for_part(part_id: u32, face: u32) -> FaceUV {
    switch part_id {
        case 0u  { return uv_head[face]; }
        case 1u  { return uv_body[face]; }
        case 2u  { return uv_rarm[face]; }
        case 3u  { return uv_larm[face]; }
        case 4u  { return uv_rleg[face]; }
        case 5u  { return uv_lleg[face]; }
        case 6u  { return uv_head_ov[face]; }
        case 7u  { return uv_body_ov[face]; }
        case 8u  { return uv_rarm_ov[face]; }
        case 9u  { return uv_larm_ov[face]; }
        case 10u { return uv_rleg_ov[face]; }
        default  { return uv_lleg_ov[face]; }
    }
}

// ── camera ────────────────────────────────────────────────────────

fn projection() -> mat4x4f {
    let fov = 3.14159265359 / 3.0;
    let near = 0.1; let far = 10.0;
    let f = 1.0 / tan(fov * 0.5);
    let aspect = uniforms.aspect;
    return mat4x4f(
        vec4f(f/aspect,0,0,0), vec4f(0,f,0,0),
        vec4f(0,0,-far/(far-near),-1), vec4f(0,0,-(far*near)/(far-near),0),
    );
}
fn view() -> mat4x4f {
    return mat4x4f(
        vec4f(1,0,0,0), vec4f(0,1,0,0), vec4f(0,0,1,0), vec4f(0,0,-4,1),
    );
}

// ── vertex shader ─────────────────────────────────────────────────

@vertex
fn vs_main(@builtin(vertex_index) id: u32) -> VertexOutput {
    let part_id   = id / 36u;
    let vertex_id = id % 36u;
    let part      = parts[part_id];
    let face      = vertex_id / 6u;

    var sz = part.size;
    // Apply slim arm width for base arms (2,3) and overlay arms (8,9)
    if (part_id == 2u || part_id == 3u || part_id == 8u || part_id == 9u) {
        sz.x *= 1.0 - uniforms.isSlim * 0.25;
    }
    var p = cube[vertex_id] * sz;

    // Limb swing animation
    let phase = phases[part_id];
    if phase != 0.0 {
        let speed = 4.0;
        let max_angle = 0.6;
        let angle = max_angle * sin(uniforms.time * speed) * phase;
        let pivot = vec3f(0.0, pivot_y, 0.0);
        p = (rotate_x(angle) * vec4f(p - pivot, 1.0)).xyz + pivot;
    }
    p += part.pos;

    let model = mul4(rotate_y(uniforms.rotY), rotate_x(-uniforms.rotX));
    let pv = mul4(mul4(projection(), view()), model);

    let fuv  = cube_uv[vertex_id];
    let rect = uv_for_part(part_id, face);
    let tex_uv = vec2f(
        rect.min.x + fuv.x * (rect.max.x - rect.min.x),
        rect.max.y - fuv.y * (rect.max.y - rect.min.y),
    );

    var out: VertexOutput;
    out.position = pv * vec4f(p * uniforms.scale, 1.0);
    out.uv       = tex_uv;
    return out;
}

// ── fragment shader ───────────────────────────────────────────────

@fragment
fn fs_main(@location(0) uv: vec2f) -> @location(0) vec4f {
    return textureSample(skin, skin_sampler, uv);
}
