// Auto-generated by scripts/generate-shader.ts
// 14 parts × 36 vertices = 504 vertices total
//
// ── Architecture ──────────────────────────────────────────────────
// GPU-first Minecraft skin renderer. A single vertex + fragment shader
// handles model transform, limb swing animation, cape pendulum physics,
// skin/cape texture sampling, and uniform scaling.
//
// Two draw calls (base + overlay) x 252 vertices = 504 total.
// CPU writes a 28-byte uniform buffer (7 × f32) each frame.
//
// ── Binding layout ────────────────────────────────────────────────
//   group(0) binding(0) — uniforms (time, camera, flags)
//   group(1) binding(0) — skin texture  (64×64 rgba8unorm)
//   group(1) binding(1) — linear sampler
//   group(1) binding(2) — cape texture (64×32 rgba8unorm, placeholder 1×1)

// ── vertex output ─────────────────────────────────────────────────
// position   — clip-space position (MVP * model vertex)
// uv         — texture coordinate (sampled from skin or cape)
// is_cape    — 1.0 for cape parts, 0.0 otherwise (fragment mix factor)
struct VertexOutput {
    @builtin(position) position: vec4f,
    @location(0) uv: vec2f,
    @location(1) is_cape: f32,
}

// ── uniform buffer (28 bytes = 7 × f32) ───────────────────────────
// Written once per frame by the CPU render loop.
// See SkinViewer.svelte → updateUniforms() for the writer.
struct Uniforms {
    time: f32,       // [0] Elapsed seconds (used for animation phases)
    rot_y: f32,      // [4] Horizontal camera rotation (radians, from pointer drag)
    rot_x: f32,      // [8] Vertical camera tilt (radians, clamped ±1.5)
    is_slim: f32,    // [12] Model variant: 0 = Steve (4px arms), 1 = Alex (3px arms)
    scale: f32,      // [16] Uniform model scale factor
    aspect: f32,     // [20] Canvas aspect ratio (width / height)
    has_cape: f32,   // [24] Cape visibility: 0 = hidden, 1 = visible
}

@group(0) @binding(0) var<uniform> uniforms: Uniforms;
@group(1) @binding(0) var skin: texture_2d<f32>;     // 64×64 skin atlas
@group(1) @binding(1) var skin_sampler: sampler;     // Nearest filtering (pixel art)
@group(1) @binding(2) var cape_tex: texture_2d<f32>; // 64×32 cape (1×1 placeholder when disabled)

// ── matrix helpers ────────────────────────────────────────────────
// WGSL has no built-in matrix multiplication for mat4x4f × mat4x4f,
// so we provide one. Rotation helpers build standard rotation matrices
// around each axis (right-handed, radians).

/// Column-wise mat4x4f multiply: a × b
fn mul4(a: mat4x4f, b: mat4x4f) -> mat4x4f {
    return mat4x4f(a * b[0], a * b[1], a * b[2], a * b[3]);
}
/// Build rotation matrix around +X axis by angle `a` (radians)
fn rotate_x(a: f32) -> mat4x4f {
    let c = cos(a); let s = sin(a);
    return mat4x4f(vec4f(1,0,0,0), vec4f(0,c,s,0), vec4f(0,-s,c,0), vec4f(0,0,0,1));
}
/// Build rotation matrix around +Y axis by angle `a` (radians)
fn rotate_y(a: f32) -> mat4x4f {
    let c = cos(a); let s = sin(a);
    return mat4x4f(vec4f(c,0,-s,0), vec4f(0,1,0,0), vec4f(s,0,c,0), vec4f(0,0,0,1));
}
/// Build rotation matrix around +Z axis by angle `a` (radians)
fn rotate_z(a: f32) -> mat4x4f {
    let c = cos(a); let s = sin(a);
    return mat4x4f(vec4f(c,s,0,0), vec4f(-s,c,0,0), vec4f(0,0,1,0), vec4f(0,0,0,1));
}

// ── cube geometry ─────────────────────────────────────────────────
// Unit cube vertices (36 = 6 faces × 2 tris × 3 verts).
// Scaled to part dimensions later via `part.size * cube[vertex_id]`.
// Face order: 0=+Z, 1=-Z, 2=+Y, 3=-Y, 4=+X, 5=-X

const cube = array<vec3f, 36>(
    vec3f(-0.5, -0.5, 0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(-0.5, -0.5, 0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(-0.5, 0.5, -0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(-0.5, 0.5, -0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(-0.5, 0.5, -0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(-0.5, -0.5, 0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(0.5, -0.5, -0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(0.5, -0.5, 0.5),
    vec3f(0.5, 0.5, -0.5),
    vec3f(0.5, 0.5, 0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(-0.5, -0.5, 0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(-0.5, -0.5, -0.5),
    vec3f(-0.5, 0.5, 0.5),
    vec3f(-0.5, 0.5, -0.5)
);

// Per-vertex unit-square UV coordinates (same for every face).
// Each face: [0,0] [1,0] [1,1] / [0,0] [1,1] [0,1]
const cube_uv = array<vec2f, 36>(
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1),
    vec2f(0,0), vec2f(1,0), vec2f(1,1),
    vec2f(0,0), vec2f(1,1), vec2f(0,1)
);

// ── body parts ────────────────────────────────────────────────────
// Each Part stores:
//   pos  — centre position in block units (model space, waist-centred)
//   size — dimensions in block units (sx, sy, sz × PX)

struct Part { pos: vec3f, size: vec3f }

// Standard (Steve) parts array: indices 0-6 = base, 7-13 = overlay
const parts = array<Part, 14>(
    Part(vec3f(0.0000, 0.7500, 0.0000), vec3f(0.5000, 0.5000, 0.5000)), // head
    Part(vec3f(0.0000, 0.1250, 0.0000), vec3f(0.5000, 0.7500, 0.2500)), // body
    Part(vec3f(-0.3750, 0.1250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // right_arm
    Part(vec3f(0.3750, 0.1250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // left_arm
    Part(vec3f(-0.1250, -0.6250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // right_leg
    Part(vec3f(0.1250, -0.6250, 0.0000), vec3f(0.2500, 0.7500, 0.2500)), // left_leg
    Part(vec3f(0.0000, 0.0000, -0.0437), vec3f(0.6250, 1.0000, 0.0625)), // cape
    Part(vec3f(0.0000, 0.7500, 0.0000), vec3f(0.5313, 0.5313, 0.5313)), // head_overlay
    Part(vec3f(0.0000, 0.1250, 0.0000), vec3f(0.5313, 0.7813, 0.2813)), // body_overlay
    Part(vec3f(-0.3750, 0.1250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)), // right_arm_overlay
    Part(vec3f(0.3750, 0.1250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)), // left_arm_overlay
    Part(vec3f(-0.1250, -0.6250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)), // right_leg_overlay
    Part(vec3f(0.1250, -0.6250, 0.0000), vec3f(0.2813, 0.7813, 0.2813)), // left_leg_overlay
    Part(vec3f(0.0000, 0.0000, -0.0437), vec3f(0.6250, 1.0000, 0.0625)) // cape_overlay
);

// Slim (Alex) arm parts: indices 0-1 = base, 2-3 = overlay
// Applied as a runtime override for part_id 2,3,9,10 when is_slim = 1.
const parts_slim = array<Part, 4>(
    Part(vec3f(-0.3438, 0.1250, 0.0000), vec3f(0.1875, 0.7500, 0.2500)), // right_arm
    Part(vec3f(0.3438, 0.1250, 0.0000), vec3f(0.1875, 0.7500, 0.2500)), // left_arm
    Part(vec3f(-0.3438, 0.1250, 0.0000), vec3f(0.2188, 0.7813, 0.2813)), // right_arm_overlay
    Part(vec3f(0.3438, 0.1250, 0.0000), vec3f(0.2188, 0.7813, 0.2813)) // left_arm_overlay
);

// Animation phase coefficient array (one per part).
// 0.0 = static (head, body, cape); ±1.0 = sin swing direction
const phases = array<f32, 14>(0.0, 0.0, 1.0, -1.0, -1.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0, -1.0, 1.0, 0.0);
// Y-coordinate of the arm/leg swing pivot (shoulder/hip joint).
// 6 px from model bottom = 0.375 block units (waist level for limbs)
const pivot_y = 0.3750f;

// ── UV rectangles per part × face ─────────────────────────────────
// FaceUV stores the min/max texture coordinates for one face.
// Each part has 6 FaceUV values (one per face, same ordering as cube[]).
// The vertex shader uses `face = vertex_id / 6` to select the correct rect.

struct FaceUV { min: vec2f, max: vec2f }

// ── 14 standard UV sets (Steve, 64×64 skin texture) ───────────────
// Cape parts (indices 6, 13) use 64×32 cape texture UVs.

const uv_head = array<FaceUV, 6>(
    FaceUV(vec2f(0.12500, 0.12500), vec2f(0.25000, 0.25000)),
    FaceUV(vec2f(0.37500, 0.12500), vec2f(0.50000, 0.25000)),
    FaceUV(vec2f(0.12500, 0.00000), vec2f(0.25000, 0.12500)),
    FaceUV(vec2f(0.25000, 0.00000), vec2f(0.37500, 0.12500)),
    FaceUV(vec2f(0.25000, 0.12500), vec2f(0.37500, 0.25000)),
    FaceUV(vec2f(0.00000, 0.12500), vec2f(0.12500, 0.25000))
);

const uv_body = array<FaceUV, 6>(
    FaceUV(vec2f(0.31250, 0.31250), vec2f(0.43750, 0.50000)),
    FaceUV(vec2f(0.50000, 0.31250), vec2f(0.62500, 0.50000)),
    FaceUV(vec2f(0.31250, 0.25000), vec2f(0.43750, 0.31250)),
    FaceUV(vec2f(0.43750, 0.25000), vec2f(0.56250, 0.31250)),
    FaceUV(vec2f(0.43750, 0.31250), vec2f(0.50000, 0.50000)),
    FaceUV(vec2f(0.25000, 0.31250), vec2f(0.31250, 0.50000))
);

const uv_rarm = array<FaceUV, 6>(
    FaceUV(vec2f(0.68750, 0.31250), vec2f(0.75000, 0.50000)),
    FaceUV(vec2f(0.81250, 0.31250), vec2f(0.87500, 0.50000)),
    FaceUV(vec2f(0.68750, 0.25000), vec2f(0.75000, 0.31250)),
    FaceUV(vec2f(0.75000, 0.25000), vec2f(0.81250, 0.31250)),
    FaceUV(vec2f(0.75000, 0.31250), vec2f(0.81250, 0.50000)),
    FaceUV(vec2f(0.62500, 0.31250), vec2f(0.68750, 0.50000))
);

const uv_larm = array<FaceUV, 6>(
    FaceUV(vec2f(0.56250, 0.81250), vec2f(0.62500, 1.00000)),
    FaceUV(vec2f(0.68750, 0.81250), vec2f(0.75000, 1.00000)),
    FaceUV(vec2f(0.56250, 0.75000), vec2f(0.62500, 0.81250)),
    FaceUV(vec2f(0.62500, 0.75000), vec2f(0.68750, 0.81250)),
    FaceUV(vec2f(0.62500, 0.81250), vec2f(0.68750, 1.00000)),
    FaceUV(vec2f(0.50000, 0.81250), vec2f(0.56250, 1.00000))
);

const uv_rleg = array<FaceUV, 6>(
    FaceUV(vec2f(0.06250, 0.31250), vec2f(0.12500, 0.50000)),
    FaceUV(vec2f(0.18750, 0.31250), vec2f(0.25000, 0.50000)),
    FaceUV(vec2f(0.06250, 0.25000), vec2f(0.12500, 0.31250)),
    FaceUV(vec2f(0.12500, 0.25000), vec2f(0.18750, 0.31250)),
    FaceUV(vec2f(0.12500, 0.31250), vec2f(0.18750, 0.50000)),
    FaceUV(vec2f(0.00000, 0.31250), vec2f(0.06250, 0.50000))
);

const uv_lleg = array<FaceUV, 6>(
    FaceUV(vec2f(0.31250, 0.81250), vec2f(0.37500, 1.00000)),
    FaceUV(vec2f(0.43750, 0.81250), vec2f(0.50000, 1.00000)),
    FaceUV(vec2f(0.31250, 0.75000), vec2f(0.37500, 0.81250)),
    FaceUV(vec2f(0.37500, 0.75000), vec2f(0.43750, 0.81250)),
    FaceUV(vec2f(0.37500, 0.81250), vec2f(0.43750, 1.00000)),
    FaceUV(vec2f(0.25000, 0.81250), vec2f(0.31250, 1.00000))
);

const uv_cape = array<FaceUV, 6>(
    FaceUV(vec2f(0.01563, 0.03125), vec2f(0.17188, 0.53125)),
    FaceUV(vec2f(0.18750, 0.03125), vec2f(0.34375, 0.53125)),
    FaceUV(vec2f(0.01563, 0.00000), vec2f(0.17188, 0.03125)),
    FaceUV(vec2f(0.17188, 0.00000), vec2f(0.32813, 0.03125)),
    FaceUV(vec2f(0.17188, 0.03125), vec2f(0.18750, 0.53125)),
    FaceUV(vec2f(0.00000, 0.03125), vec2f(0.01563, 0.53125))
);

const uv_head_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.62500, 0.12500), vec2f(0.75000, 0.25000)),
    FaceUV(vec2f(0.87500, 0.12500), vec2f(1.00000, 0.25000)),
    FaceUV(vec2f(0.62500, 0.00000), vec2f(0.75000, 0.12500)),
    FaceUV(vec2f(0.75000, 0.00000), vec2f(0.87500, 0.12500)),
    FaceUV(vec2f(0.75000, 0.12500), vec2f(0.87500, 0.25000)),
    FaceUV(vec2f(0.50000, 0.12500), vec2f(0.62500, 0.25000))
);

const uv_body_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.31250, 0.56250), vec2f(0.43750, 0.75000)),
    FaceUV(vec2f(0.50000, 0.56250), vec2f(0.62500, 0.75000)),
    FaceUV(vec2f(0.31250, 0.50000), vec2f(0.43750, 0.56250)),
    FaceUV(vec2f(0.43750, 0.50000), vec2f(0.56250, 0.56250)),
    FaceUV(vec2f(0.43750, 0.56250), vec2f(0.50000, 0.75000)),
    FaceUV(vec2f(0.25000, 0.56250), vec2f(0.31250, 0.75000))
);

const uv_rarm_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.68750, 0.56250), vec2f(0.75000, 0.75000)),
    FaceUV(vec2f(0.81250, 0.56250), vec2f(0.87500, 0.75000)),
    FaceUV(vec2f(0.68750, 0.50000), vec2f(0.75000, 0.56250)),
    FaceUV(vec2f(0.75000, 0.50000), vec2f(0.81250, 0.56250)),
    FaceUV(vec2f(0.75000, 0.56250), vec2f(0.81250, 0.75000)),
    FaceUV(vec2f(0.62500, 0.56250), vec2f(0.68750, 0.75000))
);

const uv_larm_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.81250, 0.81250), vec2f(0.87500, 1.00000)),
    FaceUV(vec2f(0.93750, 0.81250), vec2f(1.00000, 1.00000)),
    FaceUV(vec2f(0.81250, 0.75000), vec2f(0.87500, 0.81250)),
    FaceUV(vec2f(0.87500, 0.75000), vec2f(0.93750, 0.81250)),
    FaceUV(vec2f(0.87500, 0.81250), vec2f(0.93750, 1.00000)),
    FaceUV(vec2f(0.75000, 0.81250), vec2f(0.81250, 1.00000))
);

const uv_rleg_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.06250, 0.56250), vec2f(0.12500, 0.75000)),
    FaceUV(vec2f(0.18750, 0.56250), vec2f(0.25000, 0.75000)),
    FaceUV(vec2f(0.06250, 0.50000), vec2f(0.12500, 0.56250)),
    FaceUV(vec2f(0.12500, 0.50000), vec2f(0.18750, 0.56250)),
    FaceUV(vec2f(0.12500, 0.56250), vec2f(0.18750, 0.75000)),
    FaceUV(vec2f(0.00000, 0.56250), vec2f(0.06250, 0.75000))
);

const uv_lleg_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.06250, 0.81250), vec2f(0.12500, 1.00000)),
    FaceUV(vec2f(0.18750, 0.81250), vec2f(0.25000, 1.00000)),
    FaceUV(vec2f(0.06250, 0.75000), vec2f(0.12500, 0.81250)),
    FaceUV(vec2f(0.12500, 0.75000), vec2f(0.18750, 0.81250)),
    FaceUV(vec2f(0.12500, 0.81250), vec2f(0.18750, 1.00000)),
    FaceUV(vec2f(0.00000, 0.81250), vec2f(0.06250, 1.00000))
);

const uv_cape_ov = array<FaceUV, 6>(
    FaceUV(vec2f(0.01563, 0.03125), vec2f(0.17188, 0.53125)),
    FaceUV(vec2f(0.18750, 0.03125), vec2f(0.34375, 0.53125)),
    FaceUV(vec2f(0.01563, 0.00000), vec2f(0.17188, 0.03125)),
    FaceUV(vec2f(0.17188, 0.00000), vec2f(0.32813, 0.03125)),
    FaceUV(vec2f(0.17188, 0.03125), vec2f(0.18750, 0.53125)),
    FaceUV(vec2f(0.00000, 0.03125), vec2f(0.01563, 0.53125))
);

// ── 4 slim-arm UV variant sets (Alex, 64×64 skin texture) ─────────
// Only the arm parts (2=rarm, 3=larm, 9=rarm_ov, 10=larm_ov) need
// slim variants. Non-arm parts fall through to the standard UV above.

const uv_rarm_slim = array<FaceUV, 6>(
    FaceUV(vec2f(0.68750, 0.31250), vec2f(0.73438, 0.50000)),
    FaceUV(vec2f(0.79688, 0.31250), vec2f(0.84375, 0.50000)),
    FaceUV(vec2f(0.68750, 0.25000), vec2f(0.73438, 0.31250)),
    FaceUV(vec2f(0.73438, 0.25000), vec2f(0.78125, 0.31250)),
    FaceUV(vec2f(0.73438, 0.31250), vec2f(0.79688, 0.50000)),
    FaceUV(vec2f(0.62500, 0.31250), vec2f(0.68750, 0.50000))
);

const uv_larm_slim = array<FaceUV, 6>(
    FaceUV(vec2f(0.56250, 0.81250), vec2f(0.60938, 1.00000)),
    FaceUV(vec2f(0.67188, 0.81250), vec2f(0.71875, 1.00000)),
    FaceUV(vec2f(0.56250, 0.75000), vec2f(0.60938, 0.81250)),
    FaceUV(vec2f(0.60938, 0.75000), vec2f(0.65625, 0.81250)),
    FaceUV(vec2f(0.60938, 0.81250), vec2f(0.67188, 1.00000)),
    FaceUV(vec2f(0.50000, 0.81250), vec2f(0.56250, 1.00000))
);

const uv_rarm_ov_slim = array<FaceUV, 6>(
    FaceUV(vec2f(0.68750, 0.56250), vec2f(0.73438, 0.75000)),
    FaceUV(vec2f(0.79688, 0.56250), vec2f(0.84375, 0.75000)),
    FaceUV(vec2f(0.68750, 0.50000), vec2f(0.73438, 0.56250)),
    FaceUV(vec2f(0.73438, 0.50000), vec2f(0.78125, 0.56250)),
    FaceUV(vec2f(0.73438, 0.56250), vec2f(0.79688, 0.75000)),
    FaceUV(vec2f(0.62500, 0.56250), vec2f(0.68750, 0.75000))
);

const uv_larm_ov_slim = array<FaceUV, 6>(
    FaceUV(vec2f(0.81250, 0.81250), vec2f(0.85938, 1.00000)),
    FaceUV(vec2f(0.92188, 0.81250), vec2f(0.96875, 1.00000)),
    FaceUV(vec2f(0.81250, 0.75000), vec2f(0.85938, 0.81250)),
    FaceUV(vec2f(0.85938, 0.75000), vec2f(0.90625, 0.81250)),
    FaceUV(vec2f(0.85938, 0.81250), vec2f(0.92188, 1.00000)),
    FaceUV(vec2f(0.75000, 0.81250), vec2f(0.81250, 1.00000))
);

/// Look up the FaceUV for a given part, face, and body type.
/// is_slim selects between Steve (0) and Alex (non-zero) UV rects
/// for the four arm parts.
fn uv_for_part(part_id: u32, face: u32, is_slim: f32) -> FaceUV {
    switch part_id {
        case 0u  { return uv_head[face]; }
        case 1u  { return uv_body[face]; }
        case 2u  { if (is_slim != 0.0) { return uv_rarm_slim[face]; } else { return uv_rarm[face]; } }
        case 3u  { if (is_slim != 0.0) { return uv_larm_slim[face]; } else { return uv_larm[face]; } }
        case 4u  { return uv_rleg[face]; }
        case 5u  { return uv_lleg[face]; }
        case 6u  { return uv_cape[face]; }
        case 7u  { return uv_head_ov[face]; }
        case 8u  { return uv_body_ov[face]; }
        case 9u  { if (is_slim != 0.0) { return uv_rarm_ov_slim[face]; } else { return uv_rarm_ov[face]; } }
        case 10u { if (is_slim != 0.0) { return uv_larm_ov_slim[face]; } else { return uv_larm_ov[face]; } }
        case 11u { return uv_rleg_ov[face]; }
        case 12u { return uv_lleg_ov[face]; }
        default  { return uv_cape_ov[face]; }
    }
}

// ── camera ────────────────────────────────────────────────────────
// Perspective projection: 60° FOV, clip planes 0.1–10.0.
// Camera orbits on a sphere (radius = 4) around the model origin.
//   rot_y  = longitude (yaw)   — horizontal orbit around Y axis
//   rot_x  = latitude (pitch)  — vertical angle, clamped ±1.5 rad
// The camera always looks at the origin with a fixed world-up vector
// (+Y), so no roll is introduced regardless of orbit position.

/// Perspective projection matrix (60° FOV, dynamic aspect ratio)
fn projection() -> mat4x4f {
    let fov = 3.14159265359 / 3.0; // 60° in radians
    let near = 0.1; let far = 10.0;
    let f = 1.0 / tan(fov * 0.5);
    let aspect = uniforms.aspect;
    return mat4x4f(
        vec4f(f/aspect,0,0,0), vec4f(0,f,0,0),
        vec4f(0,0,-far/(far-near),-1), vec4f(0,0,-(far*near)/(far-near),0),
    );
}
/// lookAt view matrix for a +Z-forward convention (matching the
/// projection matrix). Uses `eye - tgt` for forward so that the
/// camera looks toward +Z, not -Z.
fn lookAt(eye: vec3f, tgt: vec3f, up: vec3f) -> mat4x4f {
    let f = normalize(eye - tgt);
    let r = normalize(cross(up, f));
    let u = cross(f, r);
    return mat4x4f(
        vec4f(r.x, u.x, f.x, 0.0),
        vec4f(r.y, u.y, f.y, 0.0),
        vec4f(r.z, u.z, f.z, 0.0),
        vec4f(-dot(r, eye), -dot(u, eye), -dot(f, eye), 1.0),
    );
}
/// Spherical orbit camera view matrix.
/// Camera sits on a sphere of radius 4, positioned by longitude (rot_y)
/// and latitude (rot_x). Always looks at the origin. No roll.
fn camera_view() -> mat4x4f {
    let d = 4.0;
    let eye = vec3f(
        d * cos(uniforms.rot_x) * sin(uniforms.rot_y),
        d * sin(uniforms.rot_x),
        d * cos(uniforms.rot_x) * cos(uniforms.rot_y),
    );
    return lookAt(eye, vec3f(0.0), vec3f(0.0, 1.0, 0.0));
}

// ── vertex shader ─────────────────────────────────────────────────
// The @builtin(vertex_index) encodes two pieces of information:
//   part_id   = vertex_index / 36   (which of the 14 body parts)
//   vertex_id = vertex_index % 36   (which of the 36 cube vertices)
//   face      = vertex_id / 6       (which of the 6 cube faces)

@vertex
fn vs_main(@builtin(vertex_index) id: u32) -> VertexOutput {
    let part_id   = id / 36u;
    let vertex_id = id % 36u;
    var part      = parts[part_id];
    let face      = vertex_id / 6u;

    // ── slim arm override ─────────────────────────────────────────
    // For arm parts (2, 3 = base; 9, 10 = overlay), swap in the slim
    // part definition when uniforms.is_slim = 1 (Alex model).
    // parts_slim[0..1] = base arms, parts_slim[2..3] = overlay arms.
    if (part_id == 2u || part_id == 3u || part_id == 9u || part_id == 10u) {
        if (uniforms.is_slim != 0.0) {
            var slim_part_id = 0u;
            if (part_id == 2u || part_id == 3u) {
            slim_part_id = part_id - 2u;    // part_id 2→0, 3→1 (base arms)
            }else{
            slim_part_id = part_id - 7u;    // part_id 9→2, 10→3 (overlay arms)
            }
            part=parts_slim[slim_part_id];
        }
    }
    let sz = part.size;

    // Start from the unit cube, scaled to part dimensions
    var p = cube[vertex_id] * sz;

    // ── limb swing animation (all parts except cape: 0-5, 7-12) ──
    // Exclude cape (indices 6, 13) — it has its own animation below.
    if (part_id != 6u && part_id != 13u) {
        let phase = phases[part_id];
        if phase != 0.0 {
            // Classical sine-wave limb swing around pivot_y (shoulder/hip)
            let speed = 4.0;          // Frequency multiplier (walk cycles / sec)
            let max_angle = 0.6;      // ~34° maximum swing amplitude
            let angle = max_angle * sin(uniforms.time * speed) * phase;

            // Arms swing about shoulder (Y = pivot_y = 0.375 block),
            // legs swing about hip (same Y level in our simplified model).
            let pivot = vec3f(0.0, pivot_y, 0.0);
            p = (rotate_x(angle) * vec4f(p - pivot, 1.0)).xyz + pivot;
        }
    }

    // ── cape animation (part_id 6 = base, 13 = overlay) ─────────
    if (part_id == 6u || part_id == 13u) {
        if (uniforms.has_cape == 0.0) {
            // Cape disabled: collapse to origin (invisible)
            p = vec3f(0.0);
        } else {
            // Cape pivot is the top-centre of the cape rectangle
            // (at the same height as body centre = attachment point).
            let cape_pivot = vec3f(0.0, part.pos.y + part.size.y * 0.5, part.pos.z);

            // Minecraft cape animation approximated on GPU:
            //   angle_x = 0.60 rad (~34°) base tilt + sinusoidal flap
            //   flap amplitude ≈ 0.07 rad (~4°), frequency = 2× walk speed
            //
            // The cape +Z face is the outward-facing side ((-Z) in our
            // coordinate since it sits on the back). The animation:
            //   1. Rotate 180° around Y so the +Z face points -Z (backward)
            //   2. Tilt around X (negative = lean backward/away from body)
            let walk   = uniforms.time * 4.0;
            let flap   = sin(walk * 2.0) * 0.07;   // ~4° flap amplitude
            let angle_x = 0.60 + flap;              // base tilt + flap

            let cape_rot = mul4(rotate_y(3.14159), rotate_x(-angle_x));
            p = (cape_rot * vec4f(p - cape_pivot, 1.0)).xyz + cape_pivot;
        }
    }

    // Translate from local part space to model space
    p += part.pos;

    // ── model-view-projection transform ───────────────────────────
    // Camera orbits the model on a sphere (spherical coordinates).
    // The camera position is computed from rot_y (longitude) and
    // rot_x (latitude), then a lookAt matrix targets the origin.
    // No model rotation is needed — the camera moves instead.
    let pv = mul4(projection(), camera_view());

    // ── texture coordinate lookup ─────────────────────────────────
    // Map from unit-square UV (cube_uv) to the texture rect for this
    // face. Y is flipped (texture origin is top-left, NDC is bottom-up).
    let fuv  = cube_uv[vertex_id];
    let rect = uv_for_part(part_id, face, uniforms.is_slim);
    let tex_uv = vec2f(
        rect.min.x + fuv.x * (rect.max.x - rect.min.x),
        rect.max.y - fuv.y * (rect.max.y - rect.min.y),
    );

    var out: VertexOutput;
    out.position = pv * vec4f(p * uniforms.scale, 1.0);
    out.uv       = tex_uv;
    out.is_cape  = f32(part_id == 6u || part_id == 13u);
    return out;
}

// ── fragment shader ───────────────────────────────────────────────
// Samples the skin texture (base) and cape texture, then blends them
// using the is_cape flag from the vertex shader.
// Cape parts use the cape texture; all other parts use the skin texture.
// The canvas uses premultiplied alpha (transparent background for Svelte UI overlay).

@fragment
fn fs_main(@location(0) uv: vec2f, @location(1) is_cape: f32) -> @location(0) vec4f {
    let base = textureSample(skin, skin_sampler, uv);
    let cape = textureSample(cape_tex, skin_sampler, uv);
    return mix(base, cape, is_cape);
}
